### ISSUE TITLE
Makefile has become non-generic

### ISSUE THREAD

**Issue by Mach12** [ISART-GP2018/uber_makefile#2]
Latest commit for the uber_makefile made it specific to only certain architectures, and gave a specific name to the output, whereas the file is supposedly useable for any project. Please revert changes that prevent using the file cross-project.

**Comment by Daemencer** [comment]
Target name can be changed by a single edit, if that's the only thing bothering you, I don't think it's necessary to commit a new version just for that as you will, regardless of the project, have to add a target, so having one already there isn't a big deal.

**Comment by Daemencer** [comment]
The makefile serves as an example as you will have to make it specific for any project architecture you will work on/with. Having the SFML libraries by default already makes it specific, but I went ahead and changed the INCLUDES as well as TARGET name, leaving the rest as it was.

You're free to modify it yourself next time as you are also owner of the repo.
